/*
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 * This file has been auto-generated by the confdc compiler.
 * Source: bgp.fxs
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 */

#ifndef _BGP_H_
#define _BGP_H_

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */

#ifndef bgpd__ns
#define bgpd__ns 1675405298
#define bgpd__ns_id "http://example.com/ns/bgp"
#define bgpd__ns_uri "http://example.com/ns/bgp"
#endif

#define bgpd_router_id 519485925
#define bgpd_neighbor 81789621
#define bgpd_submask 804232787
#define bgpd_bgp 555337807
#define bgpd_ip_address 36594129
#define bgpd_router 532320551
#define bgpd_as 388223143
#define bgpd_network 873253992
#define bgpd_conf 909294620
#define bgpd_mask 1167181041

#ifdef __cplusplus
}
#endif

#endif
